const data = {
  products: [
    {
      _id: "1",
      name: "하이커머스",
      category: "주방가전",
      image: "/images/하이커머스썸네일.jpg",
      price: 120000,
      countInStock: 10,
      brand: "PN",
      rating: 4.5,
      numReviews: 10,
      description: "만능 전기 압력 솥, 편리한 조리",
    },
    {
      _id: "2",
      name: "하이클래드 뉴하이브IH-6인",
      category: "압력솥",
      image: "/images/하이클래드 뉴하이브IH-6인.jpg",
      price: 100000,
      countInStock: 20,
      brand: "PN",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "핸드블렌더-1",
      category: "주방소품",
      image: "/images/핸드블렌더-1.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "휴대용가스렌지_스텐다드",
      category: "휴대용가스렌지",
      image: "/images/휴대용가스렌지_스텐다드_001.jpg",
      price: 20000,
      countInStock: 15,
      brand: "클래드",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "포시아레드",
      category: "냄비",
      image: "/images/추가-포시아레드.jpg",
      price: 65000,
      countInStock: 5,
      brand: "PN",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "스텐우드",
      category: "주방소품",
      image: "/images/스텐우드.jpg",
      price: 13900,
      countInStock: 12,
      brand: "PN",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
